
services:
  postgres:
    container_name: postgresProject
    image: postgres:18.1
    environment:
      POSTGRES_DB: projectdb
      POSTGRES_USER: projectuser
      POSTGRES_PASSWORD: 12345project
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U projectuser -d projectdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  generator:
    container_name: generatorProject
    build: ./generator
    depends_on:
      postgres:
       condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_NAME: projectdb
      DB_USER: projectuser
      DB_PASSWORD: 12345project
    restart: unless-stopped