version: '3.8'

services:
  postgres:
    container_name: postgresProject
    image: postgres:18.1
    environment:
      POSTGRES_DB: "projectdb"
      POSTGRES_USER: "projectuser"
      POSTGRES_PASSWORD: "12345project"
    ports:
      - "5432:5432"

  generator:
    container_name: generatorProject
    build: ./generator
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: projectdb
      DB_USER: projectuser
      DB_PASSWORD: 12345project



